package syntacticanalyzer.backend.enums;

public enum Token {
    NUMERO, IDENTIFICADOR, LITERAL, COMENTARIO,
    ASIGNACION, SUMA, MULTIPLICACION, ESCRIBIR, FIN, REPETIR, INICIAR,
    SI, VERDADERO, FALSO, ENTONCES, PA, PC, ERROR
}
